run:
  timeout: 5m
  go: "1.21"

linters-settings:
  govet:
    enable:
      - nilness
      - unusedwrite
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  gosimple:
    checks: ["all"]
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "use standard log package instead"

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - lll
    - text: "weak cryptographic primitive"
      linters:
        - gosec